In [5]:
import pandas as pd
import numpy as np
from wordcloud import WordCloud
import matplotlib.pyplot as plt

In [6]:
myArr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
myArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
sum(myArr)

np.int64(78)

In [8]:
def add(myArr):
    sumNum = 0
    for i in range(len(myArr)):
        sumNum = sumNum + i
    return sumNum

In [20]:
print(add(myArr))

66


In [21]:
myArr.itemsize
myArr.size

8

In [11]:
myArr.shape

(12,)

In [12]:
myArr.reshape(2, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [13]:
myArr.ndim # Returns the dimension

1

In [14]:
# Shallow and Depp Copy
newArr = np.array([1, 2, 3, 4])

# cp1 = newArr.copy()
# newArr[0] = 100

cp1 = newArr.view()
newArr[0] = 100

id(newArr)

1518249739248

In [15]:
cp1

array([100,   2,   3,   4])

In [16]:
id(cp1)


1518238221392

In [17]:
zeros = np.zeros(10)
ones = np.ones(10)

zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# numpy Methods

# reshape()
# zeros()
# ones()
# view()
# copy()

# numpy Properties

# shape
# ndim
# itemsize
# size