### Website : Codeshare

In [54]:
import numpy as np

In [55]:
a=np.array([21,546,87,86,279,256])
sum(a)


1275

In [56]:
b=a.copy() # it will create only copy

In [57]:
b

array([ 21, 546,  87,  86, 279, 256])

In [58]:
b=a.view() # it is the mirror image of a like if change the value of a it will also change in b
a[0]=84

In [63]:
b

array([ 84, 546,  87,  86, 279, 256])

In [59]:
a.dtype # returns data type

dtype('int32')

In [60]:
a.itemsize

4

In [61]:
a.reshape(2,3)

array([[ 84, 546,  87],
       [ 86, 279, 256]])

In [62]:
a.ndim # returns dimension

1

In [66]:
c=np.zeros(3) # creates an array of zeros
c

array([0., 0., 0.])

In [69]:
d=np.ones(5) # creates an array of ones
d

array([1., 1., 1., 1., 1.])